use_frameworks!

target 'CocoaHeadsUdi_Example' do
  pod 'CocoaHeadsUdi', :path => '../'

  target 'CocoaHeadsUdi_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
